In [1]:
import pandas as pd

In [2]:
tables = pd.read_html('https://en.wikipedia.org/wiki/List_of_highest-grossing_films')
tables

[    Rank  Peak                                          Title  \
 0      1     1                                         Avatar
 1      2     1                              Avengers: Endgame
 2      3     3                       Avatar: The Way of Water
 3      4     1                                        Titanic
 4      5     3                   Star Wars: The Force Awakens
 5      6     4                         Avengers: Infinity War
 6      7     6                        Spider-Man: No Way Home
 7      8     3                                 Jurassic World
 8      9     7                                  The Lion King
 9     10    10                                 Inside Out 2 †
 10    11     3                                   The Avengers
 11    12     4                                      Furious 7
 12    13    11                              Top Gun: Maverick
 13    14    10                                      Frozen II
 14    15    14                                         Barbie
 15    16     5                        Avengers: Age of Ultron
 16    17    15                    The Super Mario Bros. Movie
 17    18     9                                  Black Panther
 18    19     3  Harry Potter and the Deathly Hallows – Part 2
 19    20     9                       Star Wars: The Last Jedi
 20    21    12                 Jurassic World: Fallen Kingdom
 21    22     5                                         Frozen
 22    23    10                           Beauty and the Beast
 23    24    15                                  Incredibles 2
 24    25    11                        The Fate of the Furious
 25    26     5                                     Iron Man 3
 26    27    10                                        Minions
 27    28    12                     Captain America: Civil War
 28    29    20                                        Aquaman
 29    30     2  The Lord of the Rings: The Return of the King
 30    31    31                         Deadpool & Wolverine †
 31    32  24RK                      Spider-Man: Far From Home
 32    33  23RK                                 Captain Marvel
 33    34   5RK                 Transformers: Dark of the Moon
 34    35     7                                        Skyfall
 35    36    10                Transformers: Age of Extinction
 36    37     7                          The Dark Knight Rises
 37    38    31                                          Joker
 38    39    32               Star Wars: The Rise of Skywalker
 39    40    30                                    Toy Story 4
 40    41  4TS3                                    Toy Story 3
 41    42     3     Pirates of the Caribbean: Dead Man's Chest
 42    43    20                   Rogue One: A Star Wars Story
 43    44    34                                        Aladdin
 44    45     2      Star Wars: Episode I – The Phantom Menace
 45    46     6    Pirates of the Caribbean: On Stranger Tides
 46    47     1                                  Jurassic Park
 47    48    24                                Despicable Me 3
 48    49    22                                   Finding Dory
 49    50     5                            Alice in Wonderland

      Worldwide gross  Year           Ref
 0     $2,923,706,026  2009    [# 1][# 2]
 1     $2,797,501,328  2019    [# 3][# 4]
 2     $2,320,250,281  2022    [# 5][# 6]
 3    T$2,257,844,554  1997    [# 7][# 8]
 4     $2,068,223,624  2015   [# 9][# 10]
 5     $2,048,359,754  2018  [# 11][# 12]
 6     $1,922,598,800  2021  [# 13][# 14]
 7     $1,671,537,444  2015  [# 15][# 16]
 8     $1,656,943,394  2019   [# 17][# 4]
 9     $1,625,994,883  2024        [# 18]
 10    $1,518,815,515  2012  [# 19][# 20]
 11    $1,515,341,399  2015  [# 21][# 22]
 12    $1,495,696,292  2022  [# 23][# 24]
 13    $1,450,026,933  2019  [# 25][# 26]
 14    $1,445,638,421  2023  [# 27][# 28]
 15    $1,402,809,540  2015  [# 29][# 22]
 16    $1,361,992,475  2023  [# 30][# 31]
 17    $1,347,280,838  2018  [# 32][# 33]
 18    $1,342,139,727  2011  [# 34][# 35]
 19    $1,332,539,889  2017  [# 36][# 37]
 20    $1,308,473,425  2018  [# 38][# 12]
 21   F$1,290,000,000  2013  [# 39][# 40]
 22    $1,263,521,126  2017  [# 41][# 42]
 23    $1,242,805,359  2018  [# 43][# 12]
 24  F8$1,238,764,765  2017  [# 44][# 42]
 25    $1,214,811,252  2013  [# 45][# 46]
 26    $1,159,444,662  2015  [# 47][# 16]
 27    $1,153,337,496  2016  [# 48][# 49]
 28    $1,148,528,393  2018  [# 50][# 12]
 29    $1,147,997,407  2003  [# 51][# 52]
 30    $1,142,616,895  2024        [# 53]
 31    $1,132,679,685  2019   [# 54][# 4]
 32    $1,128,274,794  2019  [# 55][# 56]
 33    $1,123,794,079  2011  [# 57][# 35]
 34    $1,108,594,137  2012  [# 58][# 59]
 35    $1,104,054,072  2014  [# 60][# 61]
 36    $1,081,169,825  2012  [# 62][# 63]
 37    $1,074,458,282  2019  [# 64][# 26]
 38    $1,074,144,248  2019  [# 65][# 26]
 39    $1,073,394,593  2019   [# 66][# 4]
 40    $1,066,970,811  2010  [# 67][# 68]
 41    $1,066,179,747  2006  [# 69][# 70]
 42    $1,057,420,387  2016  [# 71][# 72]
 43    $1,050,693,953  2019   [# 73][# 4]
 44    $1,046,515,409  1999   [# 74][# 8]
 45    $1,045,713,802  2011  [# 75][# 68]
 46    $1,037,535,230  1993  [# 76][# 77]
 47    $1,034,800,131  2017  [# 78][# 42]
 48    $1,028,570,942  2016  [# 79][# 80]
 49    $1,025,468,216  2010  [# 81][# 82]  ,
    Rank                         Title Worldwide gross (2023 $)  Year
 0     1            Gone with the Wind         GW$4,341,000,000  1939
 1     2                        Avatar         A1$3,957,000,000  2009
 2     3                       Titanic          T$3,677,000,000  1997
 3     4                     Star Wars           $3,563,000,000  1977
 4     5             Avengers: Endgame         AE$3,275,000,000  2019
 5     6            The Sound of Music           $2,984,000,000  1965
 6     7    E.T. the Extra-Terrestrial         ET$2,917,000,000  1982
 7     8          The Ten Commandments           $2,758,000,000  1956
 8     9                Doctor Zhivago           $2,615,000,000  1965
 9    10  Star Wars: The Force Awakens        TFA$2,577,000,000  2015,
      Year                      Title  \
 0    1915      The Birth of a Nation
 1    1916                Intolerance
 2    1917                  Cleopatra
 3    1918                     Mickey
 4    1919            The Miracle Man
 ..    ...                        ...
 145  2020  Demon Slayer: Mugen Train
 146  2021    Spider-Man: No Way Home
 147  2022   Avatar: The Way of Water
 148  2023                     Barbie
 149  2024             Inside Out 2 †

                                        Worldwide gross  \
 0    $50,000,000–100,000,000 $20,000,000+R ($5,200,...
 1                                       $1,750,000R IN
 2                                           $500,000*R
 3                                           $8,000,000
 4                                          $3,000,000R
 ..                                                 ...
 145                                       $507,119,058
 146                    $1,922,598,800 ($1,912,233,593)
 147                                     $2,320,250,281
 148                                     $1,445,638,421
 149                                     $1,625,994,883

                        Budget                   Ref
 0                    $110,000    [# 83][# 84][# 85]
 1                    $385,907              [52][53]
 2                    $300,000          [# 86][# 87]
 3                    $250,000                [# 88]
 4                    $120,000                [# 89]
 ..                        ...                   ...
 145               $15,750,000               [# 304]
 146              $200,000,000         [# 13][# 305]
 147  $350,000,000–460,000,000   [# 5][# 306][# 307]
 148  $128,000,000–145,000,000  [# 27][# 308][# 309]
 149              $200,000,000         [# 18][# 310]

 [150 rows x 5 columns],
      Established                       Title        Record-setting gross  \
 0       1915[66]       The Birth of a Nation                 $5,200,000R
 1           1940       The Birth of a Nation              $15,000,000R ‡
 2       1940[32]          Gone with the Wind                $32,000,000R
 3           1963          Gone with the Wind              $67,000,000R ‡
 4       1966[66]          The Sound of Music               $114,600,000R
 5       1971[66]          Gone with the Wind             $116,000,000R ‡
 6       1972[66]               The Godfather   $127,600,000–142,000,000R
 7   1976[89][90]                        Jaws               $193,700,000R
 8   1978[91][92]                   Star Wars  $410,000,000/$268,500,000R
 9           1982                   Star Wars              $530,000,000 ‡
 10      1983[93]  E.T. the Extra-Terrestrial    $619,000,000–664,000,000
 11          1993  E.T. the Extra-Terrestrial              $701,000,000 ‡
 12      1993[66]               Jurassic Park                $912,667,947
 13      1998[94]                     Titanic              $1,843,373,318
 14  2010[95][96]                      Avatar              $2,743,577,587
 15  2010[95][96]                      Avatar            $2,788,416,135 ‡
 16  2019[97][98]           Avengers: Endgame              $2,797,501,328
 17      2021[99]                      Avatar            $2,847,397,339 ‡
 18          2022                      Avatar            $2,923,706,026 ‡

                Ref
 0           [# 84]
 1          [# 311]
 2          [# 134]
 3          [# 312]
 4          [# 209]
 5          [# 313]
 6   [# 235][# 314]
 7          [# 250]
 8   [# 315][# 235]
 9          [# 256]
 10  [# 256][# 269]
 11         [# 316]
 12          [# 76]
 13           [# 7]
 14           [# 1]
 15           [# 1]
 16           [# 3]
 17           [# 1]
 18           [# 1]  ,
                                                      0  \
 0    Rank Series Total worldwide gross No. of films...
 1                                                 Rank
 2    1 Marvel Cinematic UniverseS † $30,972,214,952...
 3                                                    1
 4    The Infinity Saga $22,589,262,908 23 $982,141,...
 ..                                                 ...
 358                                                  2
 359                                                  3
 360                                                  4
 361  The Ballad of Songbirds & Snakes (2023) $337,3...
 362                                                NaN

                                                      1  \
 0    Rank Series Total worldwide gross No. of films...
 1                                               Series
 2    1 Marvel Cinematic UniverseS † $30,972,214,952...
 3                         Marvel Cinematic UniverseS †
 4    The Infinity Saga $22,589,262,908 23 $982,141,...
 ..                                                 ...
 358                         Mockingjay – Part 1 (2014)
 359                            The Hunger Games (2012)
 360                         Mockingjay – Part 2 (2015)
 361  The Ballad of Songbirds & Snakes (2023) $337,3...
 362            The Ballad of Songbirds & Snakes (2023)

                                                      2  \
 0    Rank Series Total worldwide gross No. of films...
 1                                Total worldwide gross
 2    1 Marvel Cinematic UniverseS † $30,972,214,952...
 3                                      $30,972,214,952
 4    The Infinity Saga $22,589,262,908 23 $982,141,...
 ..                                                 ...
 358                                       $755,357,103
 359                                       $694,394,724
 360                                       $653,428,261
 361  The Ballad of Songbirds & Snakes (2023) $337,3...
 362                                       $337,371,917

                                                      3  \
 0    Rank Series Total worldwide gross No. of films...
 1                                         No. of films
 2    1 Marvel Cinematic UniverseS † $30,972,214,952...
 3                                                   34
 4    The Infinity Saga $22,589,262,908 23 $982,141,...
 ..                                                 ...
 358                                                NaN
 359                                                NaN
 360                                                NaN
 361  The Ballad of Songbirds & Snakes (2023) $337,3...
 362                                                NaN

                                                      4  \
 0    Rank Series Total worldwide gross No. of films...
 1                                     Average of films
 2    1 Marvel Cinematic UniverseS † $30,972,214,952...
 3                                         $910,947,499
 4    The Infinity Saga $22,589,262,908 23 $982,141,...
 ..                                                 ...
 358                                                NaN
 359                                                NaN
 360                                                NaN
 361  The Ballad of Songbirds & Snakes (2023) $337,3...
 362                                                NaN

                                                      5
 0    Rank Series Total worldwide gross No. of films...
 1                                Highest-grossing film
 2    1 Marvel Cinematic UniverseS † $30,972,214,952...
 3                   Avengers: Endgame ($2,797,501,328)
 4    The Infinity Saga $22,589,262,908 23 $982,141,...
 ..                                                 ...
 358                                                NaN
 359                                                NaN
 360                                                NaN
 361  The Ballad of Songbirds & Snakes (2023) $337,3...
 362                                                NaN

 [363 rows x 6 columns],
 Empty DataFrame
 Columns: [Rank, Series, Total worldwide gross, No. of films, Average of films, Highest-grossing film]
 Index: [],
                                                     0  \
 0                                                   1
 1   The Infinity Saga $22,589,262,908 23 $982,141,...
 2                                                 NaN
 3   Phase Three $13,506,562,880 11 $1,227,869,353 ...
 4                                                 NaN
 5                                                   1
 6                                                   2
 7                                                   3
 8                                                   4
 9                                                   5
 10                                                  6
 11                                                  7
 12                                                  8
 13                                                  9
 14                                                 10
 15                                                 11
 16  Phase Two $5,269,487,547 6 $878,247,925 Avenge...
 17                                                NaN
 18                                                  1
 19                                                  2
 20                                                  3
 21                                                  4
 22                                                  5
 23                                                  6
 24  Phase One $3,813,212,481 6 $635,535,414 The Av...
 25                                                NaN
 26                                                  1
 27                                                  2
 28                                                  3
 29                                                  4
 30                                                  5
 31                                                  6
 32  The Multiverse Saga † $8,382,952,044 11 $762,0...
 33                                                NaN
 34  Phase Four $5,712,571,367 7 $816,081,624 Spide...
 35                                                NaN
 36                                                  1
 37                                                  2
 38                                                  3
 39                                                  4
 40                                                  5
 41                                                  6
 42                                                  7
 43  Phase Five † $2,670,380,677 4 $667,595,169 Dea...
 44                                                NaN
 45                                                  1
 46                                                  2
 47                                                  3
 48                                                  4

                                                     1  \
 0                        Marvel Cinematic UniverseS †
 1   The Infinity Saga $22,589,262,908 23 $982,141,...
 2                                   The Infinity Saga
 3   Phase Three $13,506,562,880 11 $1,227,869,353 ...
 4                                         Phase Three
 5                            Avengers: Endgame (2019)
 6                       Avengers: Infinity War (2018)
 7                                Black Panther (2018)
 8                   Captain America: Civil War (2016)
 9                    Spider-Man: Far From Home (2019)
 10                              Captain Marvel (2019)
 11                      Spider-Man: Homecoming (2017)
 12              Guardians of the Galaxy Vol. 2 (2017)
 13                              Thor: Ragnarok (2017)
 14                              Doctor Strange (2016)
 15                        Ant-Man and the Wasp (2018)
 16  Phase Two $5,269,487,547 6 $878,247,925 Avenge...
 17                                          Phase Two
 18                     Avengers: Age of Ultron (2015)
 19                                  Iron Man 3 (2013)
 20                     Guardians of the Galaxy (2014)
 21         Captain America: The Winter Soldier (2014)
 22                        Thor: The Dark World (2013)
 23                                     Ant-Man (2015)
 24  Phase One $3,813,212,481 6 $635,535,414 The Av...
 25                                          Phase One
 26                                The Avengers (2012)
 27                                  Iron Man 2 (2010)
 28                                    Iron Man (2008)
 29                                        Thor (2011)
 30          Captain America: The First Avenger (2011)
 31                         The Incredible Hulk (2008)
 32  The Multiverse Saga † $8,382,952,044 11 $762,0...
 33                              The Multiverse Saga †
 34  Phase Four $5,712,571,367 7 $816,081,624 Spide...
 35                                         Phase Four
 36                     Spider-Man: No Way Home (2021)
 37  Doctor Strange in the Multiverse of Madness (2...
 38              Black Panther: Wakanda Forever (2022)
 39                      Thor: Love and Thunder (2022)
 40   Shang-Chi and the Legend of the Ten Rings (2021)
 41                                    Eternals (2021)
 42                                 Black Widow (2021)
 43  Phase Five † $2,670,380,677 4 $667,595,169 Dea...
 44                                       Phase Five †
 45                      Deadpool & Wolverine (2024) †
 46              Guardians of the Galaxy Vol. 3 (2023)
 47           Ant-Man and the Wasp: Quantumania (2023)
 48                                 The Marvels (2023)

                                                     2  \
 0                                     $30,972,214,952
 1   The Infinity Saga $22,589,262,908 23 $982,141,...
 2                                     $22,589,262,908
 3   Phase Three $13,506,562,880 11 $1,227,869,353 ...
 4                                     $13,506,562,880
 5                                      $2,797,501,328
 6                                      $2,048,359,754

In [3]:
df = tables[0]
df

,Rank,Peak,Title,Worldwide gross,Year,Ref
0,1,1,Avatar,"$2,923,706,026",2009,[# 1][# 2]
1,2,1,Avengers: Endgame,"$2,797,501,328",2019,[# 3][# 4]
2,3,3,Avatar: The Way of Water,"$2,320,250,281",2022,[# 5][# 6]
3,4,1,Titanic,"T$2,257,844,554",1997,[# 7][# 8]
4,5,3,Star Wars: The Force Awakens,"$2,068,223,624",2015,[# 9][# 10]
5,6,4,Avengers: Infinity War,"$2,048,359,754",2018,[# 11][# 12]
6,7,6,Spider-Man: No Way Home,"$1,922,598,800",2021,[# 13][# 14]
7,8,3,Jurassic World,"$1,671,537,444",2015,[# 15][# 16]
8,9,7,The Lion King,"$1,656,943,394",2019,[# 17][# 4]
9,10,10,Inside Out 2 †,"$1,625,994,883",2024,[# 18]
10,11,3,The Avengers,"$1,518,815,515",2012,[# 19][# 20]
11,12,4,Furious 7,"$1,515,341,399",2015,[# 21][# 22]
12,13,11,Top Gun: Maverick,"$1,495,696,292",2022,[# 23][# 24]
13,14,10,Frozen II,"$1,450,026,933",2019,[# 25][# 26]
14,15,14,Barbie,"$1,445,638,421",2023,[# 27][# 28]
15,16,5,Avengers: Age of Ultron,"$1,402,809,540",2015,[# 29][# 22]
16,17,15,The Super Mario Bros. Movie,"$1,361,992,475",2023,[# 30][# 31]
17,18,9,Black Panther,"$1,347,280,838",2018,[# 32][# 33]
18,19,3,Harry Potter and the Deathly Hallows – Part 2,"$1,342,139,727",2011,[# 34][# 35]
19,20,9,Star Wars: The Last Jedi,"$1,332,539,889",2017,[# 36][# 37]
20,21,12,Jurassic World: Fallen Kingdom,"$1,308,473,425",2018,[# 38][# 12]
21,22,5,Frozen,"F$1,290,000,000",2013,[# 39][# 40]
22,23,10,Beauty and the Beast,"$1,263,521,126",2017,[# 41][# 42]
23,24,15,Incredibles 2,"$1,242,805,359",2018,[# 43][# 12]
24,25,11,The Fate of the Furious,"F8$1,238,764,765",2017,[# 44][# 42]
25,26,5,Iron Man 3,"$1,214,811,252",2013,[# 45][# 46]
26,27,10,Minions,"$1,159,444,662",2015,[# 47][# 16]
27,28,12,Captain America: Civil War,"$1,153,337,496",2016,[# 48][# 49]
28,29,20,Aquaman,"$1,148,528,393",2018,[# 50][# 12]
29,30,2,The Lord of the Rings: The Return of the King,"$1,147,997,407",2003,[# 51][# 52]
30,31,31,Deadpool & Wolverine †,"$1,142,616,895",2024,[# 53]
31,32,24RK,Spider-Man: Far From Home,"$1,132,679,685",2019,[# 54][# 4]
32,33,23RK,Captain Marvel,"$1,128,274,794",2019,[# 55][# 56]
33,34,5RK,Transformers: Dark of the Moon,"$1,123,794,079",2011,[# 57][# 35]
34,35,7,Skyfall,"$1,108,594,137",2012,[# 58][# 59]
35,36,10,Transformers: Age of Extinction,"$1,104,054,072",2014,[# 60][# 61]
36,37,7,The Dark Knight Rises,"$1,081,169,825",2012,[# 62][# 63]
37,38,31,Joker,"$1,074,458,282",2019,[# 64][# 26]
38,39,32,Star Wars: The Rise of Skywalker,"$1,074,144,248",2019,[# 65][# 26]
39,40,30,Toy Story 4,"$1,073,394,593",2019,[# 66][# 4]
40,41,4TS3,Toy Story 3,"$1,066,970,811",2010,[# 67][# 68]
41,42,3,Pirates of the Caribbean: Dead Man's Chest,"$1,066,179,747",2006,[# 69][# 70]
42,43,20,Rogue One: A Star Wars Story,"$1,057,420,387",2016,[# 71][# 72]
43,44,34,Aladdin,"$1,050,693,953",2019,[# 73][# 4]
44,45,2,Star Wars: Episode I – The Phantom Menace,"$1,046,515,409",1999,[# 74][# 8]
45,46,6,Pirates of the Caribbean: On Stranger Tides,"$1,045,713,802",2011,[# 75][# 68]
46,47,1,Jurassic Park,"$1,037,535,230",1993,[# 76][# 77]
47,48,24,Despicable Me 3,"$1,034,800,131",2017,[# 78][# 42]
48,49,22,Finding Dory,"$1,028,570,942",2016,[# 79][# 80]
49,50,5,Alice in Wonderland,"$1,025,468,216",2010,[# 81][# 82]

In [4]:
print(df.columns)

Index(['Rank', 'Peak', 'Title', 'Worldwide gross', 'Year', 'Ref'], dtype='object')

In [5]:
df = df.drop(columns = ['Ref'])

In [6]:
print(df.columns)

Index(['Rank', 'Peak', 'Title', 'Worldwide gross', 'Year'], dtype='object')

In [7]:
df

,Rank,Peak,Title,Worldwide gross,Year
0,1,1,Avatar,"$2,923,706,026",2009
1,2,1,Avengers: Endgame,"$2,797,501,328",2019
2,3,3,Avatar: The Way of Water,"$2,320,250,281",2022
3,4,1,Titanic,"T$2,257,844,554",1997
4,5,3,Star Wars: The Force Awakens,"$2,068,223,624",2015
5,6,4,Avengers: Infinity War,"$2,048,359,754",2018
6,7,6,Spider-Man: No Way Home,"$1,922,598,800",2021
7,8,3,Jurassic World,"$1,671,537,444",2015
8,9,7,The Lion King,"$1,656,943,394",2019
9,10,10,Inside Out 2 †,"$1,625,994,883",2024
10,11,3,The Avengers,"$1,518,815,515",2012
11,12,4,Furious 7,"$1,515,341,399",2015
12,13,11,Top Gun: Maverick,"$1,495,696,292",2022
13,14,10,Frozen II,"$1,450,026,933",2019
14,15,14,Barbie,"$1,445,638,421",2023
15,16,5,Avengers: Age of Ultron,"$1,402,809,540",2015
16,17,15,The Super Mario Bros. Movie,"$1,361,992,475",2023
17,18,9,Black Panther,"$1,347,280,838",2018
18,19,3,Harry Potter and the Deathly Hallows – Part 2,"$1,342,139,727",2011
19,20,9,Star Wars: The Last Jedi,"$1,332,539,889",2017
20,21,12,Jurassic World: Fallen Kingdom,"$1,308,473,425",2018
21,22,5,Frozen,"F$1,290,000,000",2013
22,23,10,Beauty and the Beast,"$1,263,521,126",2017
23,24,15,Incredibles 2,"$1,242,805,359",2018
24,25,11,The Fate of the Furious,"F8$1,238,764,765",2017
25,26,5,Iron Man 3,"$1,214,811,252",2013
26,27,10,Minions,"$1,159,444,662",2015
27,28,12,Captain America: Civil War,"$1,153,337,496",2016
28,29,20,Aquaman,"$1,148,528,393",2018
29,30,2,The Lord of the Rings: The Return of the King,"$1,147,997,407",2003
30,31,31,Deadpool & Wolverine †,"$1,142,616,895",2024
31,32,24RK,Spider-Man: Far From Home,"$1,132,679,685",2019
32,33,23RK,Captain Marvel,"$1,128,274,794",2019
33,34,5RK,Transformers: Dark of the Moon,"$1,123,794,079",2011
34,35,7,Skyfall,"$1,108,594,137",2012
35,36,10,Transformers: Age of Extinction,"$1,104,054,072",2014
36,37,7,The Dark Knight Rises,"$1,081,169,825",2012
37,38,31,Joker,"$1,074,458,282",2019
38,39,32,Star Wars: The Rise of Skywalker,"$1,074,144,248",2019
39,40,30,Toy Story 4,"$1,073,394,593",2019
40,41,4TS3,Toy Story 3,"$1,066,970,811",2010
41,42,3,Pirates of the Caribbean: Dead Man's Chest,"$1,066,179,747",2006
42,43,20,Rogue One: A Star Wars Story,"$1,057,420,387",2016
43,44,34,Aladdin,"$1,050,693,953",2019
44,45,2,Star Wars: Episode I – The Phantom Menace,"$1,046,515,409",1999
45,46,6,Pirates of the Caribbean: On Stranger Tides,"$1,045,713,802",2011
46,47,1,Jurassic Park,"$1,037,535,230",1993
47,48,24,Despicable Me 3,"$1,034,800,131",2017
48,49,22,Finding Dory,"$1,028,570,942",2016
49,50,5,Alice in Wonderland,"$1,025,468,216",2010

In [9]:
df.to_csv(r'C:\Users\USER\Downloads\data.csv', index = False)